global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    environment: production

scrape_configs:
  - job_name: 'producer'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names: ['producer']
        type: 'A'
        port: 8080

  - job_name: 'worker'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names: ['worker']
        type: 'A'
        port: 8080

  - job_name: 'maintenance'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names: ['maintenance']
        type: 'A'
        port: 8080

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']