spring.application.name=distributed-job-queue

# Environmental Variables
spring.config.import=optional:file:.env[.properties]

# Redis Credentials
redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}
redis.password=${REDIS_PASSWORD}