{
 "title": "Distributed Job Queue",
 "description": "Built a monitoring dashboard for a distributed job queue system to visualize task lifecycle states (queued, processing, completed, failed), worker node activity, and queue latency. Integrated real-time metrics and logs to track throughput, retries, and failure patterns, enabling faster diagnosis of bottlenecks and system resilience issues in a distributed environment.",
 "tags": [
  "redis",
  "postgres",
  "java",
  "spring",
  "docker",
  "prometheus",
  "grafana",
  "job-queue"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Processing Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(job_processing_queue_depth)",
     "legendFormat": "Processing"
    }
   ]
  },
  {
   "title": "Main Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(job_queue_depth)", "legendFormat": "Waiting" }
   ]
  },
  {
   "title": "Retry Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(job_retry_queue_depth)", "legendFormat": "Retry Queue" }
   ]
  },
  {
   "title": "Dead Letter Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(job_dlq_depth)", "legendFormat": "DLQ" }
   ]
  },
  {
   "title": "Job Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(job_enqueued_total[1m]))",
     "legendFormat": "Enqueued"
    },
    {
     "expr": "sum(rate(job_completed_total[1m]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(rate(job_failed_total[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(job_retried_total[1m]))",
     "legendFormat": "Retried"
    }
   ]
  },
  {
   "title": "Success/Failure Ratio (Last Hour)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(job_completed_total[1h]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(job_failed_total[1h]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(job_dlq_total[1h]))",
     "legendFormat": "DLQ"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(instance) (up{job=~\"worker.*|maintenance|producer|redis|postgres\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(job_processing_time_seconds_sum[1m])) / sum(rate(job_processing_time_seconds_count[1m]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(job_processing_time_seconds_max{instance=~\"worker-1:8080|worker-2:8080\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "System Self-Healing Activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(job_recovered_total[5m]))",
     "legendFormat": "Jobs Recovered"
    }
   ]
  },
  {
   "title": "Consistency Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(reconciliation_missing_jobs_total[5m])) + sum(rate(reconciliation_corrupted_metadata_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "(sum(rate(job_completed_total[1m])) / (sum(rate(job_completed_total[1m])) + sum(rate(job_failed_total[1m])))) * 100",
     "legendFormat": "Succes rate"
    },
    {
     "expr": "(sum(rate(job_failed_total[1m])) / (sum(rate(job_completed_total[1m])) + sum(rate(job_failed_total[1m])))) * 100",
     "legendFormat": "Failure rate"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(job_recovered_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DLQ Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(job_dlq_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}